engines:
  csslint:
    enabled: true
    exclude_paths:
      - "assets/css/toggle-switch.css"
    checks:
      box-sizing:
        enabled: false
      gradients:
        enabled: false
  eslint:
    enabled: true
    checks:
      complexity:
        enabled: false
